[theme]
primaryColor="#123c69"
backgroundColor="#a8d0e6"
secondaryBackgroundColor="#eee2cd"
textColor="#123c69"

[deprecation]
showfileUploaderEncoding=false

# [theme] - top
# primaryColor="#123c69"
# backgroundColor="#edc7b7"
# secondaryBackgroundColor="#eee2cd"
# textColor="#123c69"

# [theme]
# primaryColor="#ac3b61"
# backgroundColor="#edc7b7"
# secondaryBackgroundColor="#eee2cd"
# textColor="#123c69"

# [theme]
# primaryColor="#f76c6c"
# backgroundColor="#a8d0e6"
# secondaryBackgroundColor="#f8e9a1"
# textColor="#374785"

# [theme]
# primaryColor="#213f99"
# backgroundColor="#ddd0c8"
# secondaryBackgroundColor="#d0c7c3"
# textColor="#323232"

# [theme]
# primaryColor="#213f99"
# backgroundColor="#e1b0ac"
# secondaryBackgroundColor="#f2d4d6"
# textColor="#213f99"
